import './globals.css'
import { Inter } from 'next/font/google'
import  Nav  from "./Components/Navbar/page";
import  Footer  from "./Components/Footer/page";
// import { url } from 'inspector';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // Image:url();
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav title={'Shaphire Resto Food Empire'}/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
